# Use the rust image as the base image
FROM rust:latest

# Install the dependencies required by Rust-TEOS
RUN apt-get update && \
    apt-get -y --no-install-recommends install libffi-dev libssl-dev pkg-config libleveldb-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Set the working directory to /srv
WORKDIR /srv

# Copy the source code into the container
COPY . /srv/rust-teos

# Build the application
WORKDIR /srv/rust-teos

#Getting [ error: 'rustfmt' is not installed for the toolchain '1.67.1-aarch64-unknown-linux-gnu'] so added a line:
RUN rustup component add rustfmt 

RUN cargo build --release

# Create a volume for the TEOS data directory
VOLUME ["/root/.teos"]

# Expose the default port used by Rust-TEOS
EXPOSE 9814/tcp

# Start Rust-TEOS when the container starts
ENTRYPOINT [ "/srv/rust-teos/docker/entrypoint.sh" ]
